### ISSUE TITLE
[Bug]: upgrade react-resize-detector for React 19 support

### ISSUE THREAD

**Issue by okize** [100mslive/web-sdks#3131]
### What happened?

When using the latest version of `@100mslive/react-sdk` in a project with React 19 this error is shown:

```
ERROR in ../node_modules/react-resize-detector/build/index.esm.js 709:33-44
export 'findDOMNode' (imported as 'findDOMNode') was not found in 'react-dom' (possible exports: __DOM_INTERNALS_DO_NOT_U)
```

This is because the `ReactDOM.findDOMNode()` method was removed in React 19 (see: https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-reactdom-finddomnode).

The `react-resize-detector` project has fixed this issue as of version 10 (see: https://github.com/maslianok/react-resize-detector/releases/tag/v10.0.0) so if we could update this https://github.com/100mslive/web-sdks/blob/main/packages/react-sdk/package.json#L52C6-L52C27 from

```json
"react-resize-detector": "^7.0.0",
``` 

to 

```json
"react-resize-detector": "^10.0.0",
``` 

it should resolve the issue. 

That version of `react-resize-detector` does drop support for React v16 & React v17, so upgrading would be a breaking change in this project as well. 

### How can we reproduce the bug?

In an existing project using the `@100mslive/react-sdk` library, run `npm install --save-exact react@rc react-dom@rc` to get v19 of React to see the error.

**Comment by raviteja83** [comment]
@okize we are not going to migrate anytime soon given we need to support 16 and 17. Feel free to fork update for your needs. Thanks for reporting the issue.
