### ISSUE TITLE
[Bug]: Some of our recordings are lost

### ISSUE THREAD

**Issue by thesujai** [100mslive/web-sdks#3306]
### What happened?

Hi I am SDE at Upraised
We conducted a hiring drive, and now when we observe some of the recording were not uploaded to s3.

I reported in the discord server but no respond from your side

**Comment by Akashgoswami1** [comment]
How to create a ticket?
Login to the 100ms dashboard (https://dashboard.100ms.live/dashboard)
On the top right, you’ll find the Support section where you can easily create tickets.
For a detailed walkthrough, check out the video here 🎥
(https://www.loom.com/share/f3f8bba844d945029232ea6aa9cc69c7)
